# Generated by Django 3.2.8 on 2021-10-19 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('representante', models.CharField(max_length=100, verbose_name='Representante')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('correoElectronico', models.CharField(max_length=15, verbose_name='Correo Electrónico')),
                ('observaciones', models.TextField(max_length=500, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Cuadra',
                'verbose_name_plural': 'Cuadras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Descuentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('porcentaje', models.FloatField(default=0, verbose_name='Porcentaje')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('abreviatura', models.CharField(max_length=100, unique=True, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Cuota',
                'verbose_name_plural': 'Tipos de Cuotas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ejemplares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('edad', models.FloatField(default=0, verbose_name='Edad')),
                ('peso', models.FloatField(default=0, verbose_name='Peso')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('padre', models.CharField(max_length=100, verbose_name='Padre del Caballo')),
                ('madre', models.CharField(max_length=100, verbose_name='Madre del Caballo')),
                ('observaciones', models.TextField(max_length=500, verbose_name='Observaciones')),
                ('cuadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.cuadras', verbose_name='Cuadra')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.nacionalidad', verbose_name='Nacionalidad')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.sexo', verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Ejemplar',
                'verbose_name_plural': 'Ejemplares',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('monto', models.FloatField(default=0, verbose_name='Monto')),
                ('tipoCuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.tipocuota', verbose_name='Tipo de Cuota')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['nombre'],
            },
        ),
    ]
