# Generated by Django 3.2.8 on 2021-10-24 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(default=0, verbose_name='Monto')),
                ('fechaVencimiento', models.DateField(auto_now=True, verbose_name='Fecha de Vencimiento')),
                ('tipoCuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.tipocuota', verbose_name='Tipo de Cuota')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('yardas', models.IntegerField(verbose_name='Distancia (yardas)')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('bolsa', models.FloatField(verbose_name='Bolsa')),
                ('fondo', models.FloatField(verbose_name='Fondo')),
                ('temporada', models.IntegerField(verbose_name='Temporada')),
                ('observaciones', models.TextField(max_length=500, verbose_name='Observaciones')),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.descuentos', verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Limite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'límite de Condición',
                'verbose_name_plural': 'límites de Condiciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCondicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Condición',
                'verbose_name_plural': 'Tipos de Condiciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Evento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoFecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Fecha del Evento',
                'verbose_name_plural': 'Fechas del Evento',
            },
        ),
        migrations.CreateModel(
            name='RegistroCuotaEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('valorRecibido', models.CharField(max_length=500, verbose_name='Valor Recibido en')),
                ('cuadras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.cuadras', verbose_name='Cuadra')),
                ('cuotaEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.cuotaevento', verbose_name='Cuotas')),
                ('ejemplares', models.ManyToManyField(to='amcm.Ejemplares', verbose_name='Ejemplares')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Registro a Evento',
                'verbose_name_plural': 'Registro a Evento',
                'ordering': ['evento'],
            },
        ),
        migrations.CreateModel(
            name='FechasEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha de Vencimiento')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.evento', verbose_name='Evento')),
                ('tipoFecha', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='amcm.tipofecha', verbose_name='Tipo de Fecha')),
            ],
            options={
                'verbose_name': 'Fechas del Evento',
                'verbose_name_plural': 'Fechas del Evento',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='tipoEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.tipoevento', verbose_name='Tipo de Evento'),
        ),
        migrations.CreateModel(
            name='CondicionesEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0, verbose_name='Valor')),
                ('especificacion', models.CharField(blank=True, max_length=500, verbose_name='Especificación de la Condición')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.evento', verbose_name='Evento')),
                ('limite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.limite', verbose_name='Limite')),
                ('tipoCondicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.tipocondicion', verbose_name='Tipo de Condición')),
            ],
            options={
                'verbose_name': 'Condición del Evento',
                'verbose_name_plural': 'Condiciones del Evento',
            },
        ),
    ]
