# Generated by Django 3.2.8 on 2021-10-24 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0002_auto_20211024_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipofecha',
            options={'verbose_name': 'Tipo de Fecha del Evento', 'verbose_name_plural': 'Tipos de Fechas del Evento'},
        ),
        migrations.AddField(
            model_name='cuotaevento',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amcm.evento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fechasevento',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de Vencimiento'),
        ),
    ]
