# Generated by Django 3.2.6 on 2021-10-25 12:33

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0004_alter_cuotaevento_fechavencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('status', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('RETIRADO', 'RETIRADO')], default='ACTIVO', max_length=15, verbose_name='Estatus de inscripción')),
                ('cuadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.cuadras', verbose_name='Cuadra')),
                ('ejemplar', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='cuadra', chained_model_field='cuadra', null=True, on_delete=django.db.models.deletion.CASCADE, to='amcm.ejemplares')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['evento'],
            },
        ),
    ]
