# Generated by Django 3.2.8 on 2021-10-25 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0004_alter_cuotaevento_fechavencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amcm.descuentos', verbose_name='Descuento'),
        ),
    ]
