# Generated by Django 3.2.8 on 2021-10-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0005_alter_evento_descuento'),
        ('amcm', '0005_inscripcion'),
    ]

    operations = [
    ]
