# Generated by Django 3.2.8 on 2021-10-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0006_merge_0005_alter_evento_descuento_0005_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadras',
            name='correoElectronico',
            field=models.CharField(max_length=100, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='cuadras',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cuadras',
            name='representante',
            field=models.CharField(max_length=150, verbose_name='Representante'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Descripción'),
        ),
    ]
