# Generated by Django 3.2.8 on 2021-10-26 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0007_auto_20211025_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuotaPagada', models.FloatField(verbose_name='Cuota Recibida')),
                ('cuotaLetra', models.CharField(max_length=500, verbose_name='Cuota en Letra')),
                ('conceptoPago', models.CharField(max_length=250, verbose_name='Concepto de Pago')),
                ('fechaPago', models.DateField(auto_now=True, verbose_name='Fecha de Pago')),
                ('fechaRegistro', models.DateField(auto_now=True, verbose_name='Fecha de Registro')),
                ('numeroRecibo', models.IntegerField(verbose_name='Recibo')),
                ('valorRecibido', models.CharField(max_length=500, verbose_name='Valor Recibido en')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.cuotaevento', verbose_name='Cuota')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.inscripcion', verbose_name='Inscripcion')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.DeleteModel(
            name='RegistroCuotaEvento',
        ),
    ]
