# Generated by Django 3.2.6 on 2021-10-27 20:58

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0008_auto_20211026_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='cuotaLetra',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='inscripcion',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='numeroRecibo',
        ),
        migrations.AddField(
            model_name='pago',
            name='cuadra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amcm.cuadras', verbose_name='Cuadra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='ejemplar',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='cuadra', chained_model_field='cuadra', null=True, to='amcm.Ejemplares'),
        ),
        migrations.AddField(
            model_name='pago',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amcm.evento', verbose_name='Evento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='conceptoPago',
            field=models.CharField(max_length=250, verbose_name='Concepto del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cuota',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='evento', chained_model_field='evento', null=True, on_delete=django.db.models.deletion.CASCADE, to='amcm.cuotaevento'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cuotaPagada',
            field=models.FloatField(verbose_name='Monto Recibido'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateField(auto_now=True, verbose_name='Fecha del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='valorRecibido',
            field=models.CharField(max_length=500, verbose_name='Valor Recibido En ...:'),
        ),
    ]
