# Generated by Django 3.2.8 on 2021-10-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0008_auto_20211026_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadras',
            name='celular',
            field=models.CharField(blank=True, max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='cuadras',
            name='correoElectronico',
            field=models.CharField(blank=True, max_length=100, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='cuadras',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='cuadras',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
    ]
