# Generated by Django 3.2.6 on 2021-10-28 19:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0012_ejemplares_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estatus_credito',
            field=models.CharField(choices=[('PAGADO', 'PAGADO'), ('CREDITO', 'CREDITO')], default='PAGADO', max_length=15, verbose_name='Estatus del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 28, 19, 55, 43, 416182, tzinfo=utc), null=True, verbose_name='Fecha del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 19, 55, 43, 416215, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2021, 10, 28, 19, 55, 43, 416925, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.FloatField(verbose_name='Importe')),
                ('fecha_registro', models.DateField(default=datetime.datetime(2021, 10, 28, 19, 55, 43, 417472, tzinfo=utc), verbose_name='Fecha de registro')),
                ('pagado', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=15, verbose_name='Pagado?')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amcm.pago', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
            },
        ),
    ]
