# Generated by Django 3.2.8 on 2021-12-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0015_auto_20211107_1552'),
        ('amcm', '0017_auto_20211215_1424'),
    ]

    operations = [
    ]
