# Generated by Django 3.2.8 on 2022-01-04 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0029_auto_20220103_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplares',
            options={'verbose_name': 'Ejemplar', 'verbose_name_plural': 'Ejemplares'},
        ),
        migrations.AddField(
            model_name='listadoelegibles',
            name='estaus',
            field=models.BooleanField(default=False, verbose_name='Retirado'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_pago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 4, 10, 25, 5, 995924, tzinfo=utc), null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 10, 25, 5, 995900, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='cuentaspago',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 10, 25, 5, 979502, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='elegible',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 10, 25, 5, 979953, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.RemoveField(
            model_name='listadoelegibles',
            name='ejemplar',
        ),
        migrations.AddField(
            model_name='listadoelegibles',
            name='ejemplar',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='cuadra', chained_model_field='cuadra', limit_choices_to={'estatus__nombre': 'ACTIVO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejemplar_elegible', to='amcm.ejemplares'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 4, 10, 25, 5, 976973, tzinfo=utc), null=True, verbose_name='Fecha del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 10, 25, 5, 977006, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 10, 25, 5, 994890, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
    ]
