# Generated by Django 3.2.6 on 2022-01-07 20:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0046_auto_20220106_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplares',
            options={'ordering': ['cuadra', 'lote'], 'verbose_name': 'Ejemplar', 'verbose_name_plural': 'Ejemplares'},
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_pago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 7, 20, 51, 45, 693024, tzinfo=utc), null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 20, 51, 45, 693024, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='cuentaspago',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 20, 51, 45, 674053, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='elegible',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 20, 51, 45, 675052, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 7, 20, 51, 45, 672054, tzinfo=utc), null=True, verbose_name='Fecha del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 20, 51, 45, 672054, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 20, 51, 45, 692024, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.CreateModel(
            name='PaquetesDescuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paquete', models.CharField(choices=[('A', 'PAQUETE A'), ('B', 'PAQUETE B'), ('C', 'PAQUETE C')], default='A', max_length=10, verbose_name='Paquete')),
                ('porcentaje_uno', models.FloatField(default=25, verbose_name='Porcentaje Primer Futurity')),
                ('porcentaje_dos', models.FloatField(default=25, verbose_name='Porcentaje Segundo Futurity')),
                ('porcentaje_tres', models.FloatField(default=25, verbose_name='Porcentaje Tercer Futurity')),
                ('porcentaje_cuatro', models.FloatField(default=50, verbose_name='Porcentaje Cuarto Futurity')),
                ('porcentaje_cinco', models.FloatField(default=50, verbose_name='Porcentaje Quinto Futurity')),
                ('anio', models.IntegerField(default=2022, verbose_name='Año')),
                ('evento_cinco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_cinco', to='amcm.evento', verbose_name='Quinto Futurity')),
                ('evento_cuatro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento_cuatro', to='amcm.evento', verbose_name='Cuarto Futurity')),
                ('evento_dos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_dos', to='amcm.evento', verbose_name='Segundo Futurity')),
                ('evento_tres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_tres', to='amcm.evento', verbose_name='Tercer Futurity')),
                ('evento_uno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_uno', to='amcm.evento', verbose_name='Primer Futurity')),
            ],
            options={
                'verbose_name': 'Paquete Descuento',
                'verbose_name_plural': 'Paquetes Descuentos',
                'ordering': ['paquete'],
            },
        ),
    ]
