# Generated by Django 3.2.6 on 2022-01-07 21:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0047_auto_20220107_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_pago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 7, 21, 0, 26, 464065, tzinfo=utc), null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 21, 0, 26, 464065, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='cuentaspago',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 21, 0, 26, 442059, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='elegible',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 21, 0, 26, 443059, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 7, 21, 0, 26, 440060, tzinfo=utc), null=True, verbose_name='Fecha del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 21, 0, 26, 440060, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='paquetesdescuento',
            name='evento_cinco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento_cinco', to='amcm.evento', verbose_name='Quinto Futurity'),
        ),
        migrations.AlterField(
            model_name='paquetesdescuento',
            name='evento_cuatro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evento_cuatro', to='amcm.evento', verbose_name='Cuarto Futurity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 7, 21, 0, 26, 463065, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
    ]
