# Generated by Django 3.2.8 on 2022-01-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0018_merge_0015_auto_20211107_1552_0017_auto_20211215_1424'),
        ('amcm', '0048_auto_20220107_1501'),
    ]

    operations = [
    ]
