# Generated by Django 3.2.6 on 2022-01-26 01:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0050_auto_20220125_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetesdescuento',
            name='ahorro',
            field=models.FloatField(default=1, verbose_name='Ahorro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquetesdescuento',
            name='importe',
            field=models.FloatField(default=1, verbose_name='Importe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_pago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 26, 1, 31, 19, 741401, tzinfo=utc), null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 26, 1, 31, 19, 741388, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='cuentaspago',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 26, 1, 31, 19, 738878, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='elegible',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 26, 1, 31, 19, 739140, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 1, 26, 1, 31, 19, 737839, tzinfo=utc), null=True, verbose_name='Fecha del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 1, 26, 1, 31, 19, 737853, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 1, 26, 1, 31, 19, 740867, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
    ]
