# Generated by Django 3.2.6 on 2022-02-17 20:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0052_auto_20220202_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocuota',
            name='tipo',
            field=models.CharField(choices=[('EVENTO', 'CUOTA PARA EVENTOS'), ('GENERAL', 'CUOTA PARA PAGOS EN GENERAL')], default='EVENTO', max_length=15, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_pago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 17, 20, 37, 35, 368943, tzinfo=utc), null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 20, 37, 35, 368931, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='cuentaspago',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 20, 37, 35, 359423, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='elegible',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 20, 37, 35, 359683, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 17, 20, 37, 35, 357821, tzinfo=utc), null=True, verbose_name='Fecha del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 20, 37, 35, 357834, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 20, 37, 35, 368426, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
    ]
