# Generated by Django 3.2.6 on 2022-02-24 19:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0055_auto_20220223_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='fecha_pago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 24, 19, 20, 51, 969220, tzinfo=utc), null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 2, 24, 19, 20, 51, 969207, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='cuentaspago',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 2, 24, 19, 20, 51, 958923, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='ejemplares',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='ejemplares',
            name='edad',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='ejemplares',
            name='madre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Madre del Caballo'),
        ),
        migrations.AlterField(
            model_name='ejemplares',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='ejemplares',
            name='padre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Padre del Caballo'),
        ),
        migrations.AlterField(
            model_name='ejemplares',
            name='peso',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='ejemplares',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amcm.sexo', verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='elegible',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 2, 24, 19, 20, 51, 959189, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 24, 19, 20, 51, 957305, tzinfo=utc), null=True, verbose_name='Fecha del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 2, 24, 19, 20, 51, 957319, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 2, 24, 19, 20, 51, 968672, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='referenciaformapago',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 2, 24, 19, 20, 51, 968266, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
    ]
