# Generated by Django 3.2.6 on 2022-04-27 23:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0057_auto_20220427_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuadra', models.CharField(max_length=150, verbose_name='NombreCuadra')),
                ('fecha_registro', models.DateField(default=datetime.datetime(2022, 4, 27, 23, 36, 45, 698296, tzinfo=utc), editable=False, verbose_name='Fecha de registro')),
                ('cuadra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='amcm.cuadras', verbose_name='Cuadra')),
            ],
            options={
                'verbose_name': 'Estado de Cuenta',
                'verbose_name_plural': 'Estado de Cuenta',
            },
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_pago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 27, 23, 36, 45, 698014, tzinfo=utc), null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 4, 27, 23, 36, 45, 698001, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='cuentaspago',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 4, 27, 23, 36, 45, 688225, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='elegible',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 4, 27, 23, 36, 45, 688491, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 27, 23, 36, 45, 686689, tzinfo=utc), null=True, verbose_name='Fecha del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 4, 27, 23, 36, 45, 686705, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 4, 27, 23, 36, 45, 697463, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='referenciaformapago',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 4, 27, 23, 36, 45, 697150, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.CreateModel(
            name='EstadoCuentaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(editable=False, verbose_name='Fecha')),
                ('concepto', models.CharField(blank=True, max_length=500, null=True, verbose_name='Concepto')),
                ('debe', models.FloatField(verbose_name='Debe')),
                ('haber', models.FloatField(verbose_name='Haber')),
                ('saldo', models.FloatField(verbose_name='Saldo')),
                ('fecha_registro', models.DateField(default=datetime.datetime(2022, 4, 27, 23, 36, 45, 698568, tzinfo=utc), editable=False, verbose_name='Fecha de registro')),
                ('estado_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='amcm.estadocuenta', verbose_name='Cuadra')),
            ],
            options={
                'verbose_name': 'Detalle Estado de Cuenta',
                'verbose_name_plural': 'Detalle Estado de Cuenta',
            },
        ),
    ]
