# Generated by Django 3.2.6 on 2022-05-31 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('amcm', '0063_auto_20220531_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion_fondo',
            field=models.CharField(default='', max_length=100, verbose_name='Descripción del Fondo'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_pago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 31, 19, 7, 40, 351399, tzinfo=utc), null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 5, 31, 19, 7, 40, 351386, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='cuentaspago',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 5, 31, 19, 7, 40, 341847, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='elegible',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 5, 31, 19, 7, 40, 342108, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='estadocuenta',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 19, 7, 40, 351682, tzinfo=utc), editable=False, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='estadocuentadetalle',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 19, 7, 40, 352033, tzinfo=utc), editable=False, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaPago',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 31, 19, 7, 40, 340322, tzinfo=utc), null=True, verbose_name='Fecha del Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2022, 5, 31, 19, 7, 40, 340336, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 5, 31, 19, 7, 40, 350878, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='referenciaformapago',
            name='fecha_registro',
            field=models.DateField(default=datetime.datetime(2022, 5, 31, 19, 7, 40, 350536, tzinfo=utc), verbose_name='Fecha de registro'),
        ),
    ]
